### PR TITLE
Add sample_query_options to more functions

### PR DESCRIPTION
**Pull request by leehart**
Re: issue #635

### CODE REVIEW

**Comment by leehart** [comment]
I'm starting to suspect changing these functions to kwargs-only was unnecessary, and it risks being incompatible with existing calls, although it does seem in keeping with the approach/style elsewhere in the package, and I suppose function calls can be updated... 🤔

**Comment by alimanfoo** [comment]
> I'm starting to suspect changing these functions to kwargs-only was unnecessary, and it risks being incompatible with existing calls, although it does seem in keeping with the approach/style elsewhere in the package, and I suppose function calls can be updated... 🤔

The approach I've taken so far is that private functions should be kwargs-only wherever possible, to help avoid bugs introduced by changing the order of parameters in a function call. But public functions can accept positional args.

If we changed public functions to kwargs-only we'd likely break some user code. I was tempted to do it a while back, but then thought better of it when I realised I do tend to use positional args when doing data analysis.

**Comment by leehart** [comment]
Thanks @alimanfoo . I'll amend this PR accordingly.

**Review by alimanfoo — APPROVED** [review]
LGTM, thanks @leehart!

**Pull request merged**
