### PR TITLE
Type annotations and numpydoc_decorator applied to AnophelesDataResource

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR introduces [type annotations](https://docs.python.org/3/library/typing.html) together with [numpydoc_decorator](https://github.com/alimanfoo/numpydoc_decorator) to improve maintainability of docstrings on the AnophelesDataResource class.

Towards #350.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Here is the resulting docstring on the `snp_allele_counts()` method:

```
In [5]: ag3.snp_allele_counts?
Signature:
ag3.snp_allele_counts(
    region: Union[str, malariagen_data.util.Region],
    sample_sets: Union[List[str], str, NoneType] = None,
    sample_query: Union[str, NoneType] = None,
    site_mask: Union[str, NoneType] = None,
    site_class: Union[str, NoneType] = None,
    cohort_size: Union[int, NoneType] = None,
    random_seed: Union[int, NoneType] = 42,
) -> numpy.ndarray
Docstring:
Compute SNP allele counts. This returns the number of times each SNP
allele was observed in the selected samples.

Parameters
----------
region : str or Region
    Contig name, region string (formatted like "{contig}:{start}-{end}"),
    or identifier of a genome feature such as a gene or transcript.
sample_sets : List[str] or str or None, optional
    List of sample sets and/or releases. Can also be a single sample set
    or release.
sample_query : str or None, optional
    A pandas query string to be evaluated against the sample metadata.
site_mask : str or None, optional
    Which site filters mask to apply. See the `site_mask_ids` property for
    available values.
site_class : str or None, optional
    Select sites belonging to one of the following classes: CDS_DEG_4,
    (4-fold degenerate coding sites), CDS_DEG_2_SIMPLE (2-fold simple
    degenerate coding sites), CDS_DEG_0 (non-degenerate coding sites),
    INTRON_SHORT (introns shorter than 100 bp), INTRON_LONG (introns
    longer than 200 bp), INTRON_SPLICE_5PRIME (intron within 2 bp of 5'
    splice site), INTRON_SPLICE_3PRIME (intron within 2 bp of 3' splice
    site), UTR_5PRIME (5' untranslated region), UTR_3PRIME (3'
    untranslated region), INTERGENIC (intergenic, more than 10 kbp from a
    gene).
cohort_size : int or None, optional
    Randomly down-sample to the given cohort size.
random_seed : int or None, optional, default: 42
    Random seed used for reproducible down-sampling.

Returns
-------
ndarray
    A numpy array of shape (n_variants, 4), where the first column has the
    reference allele (0) counts, the second column has the first alternate
    allele (1) counts, the third column has the second alternate allele
    (2) counts, and the fourth column has the third alternate allele (3)
    counts.

Notes
-----
This computation may take some time to run, depending on your
computing environment. Results of this computation will be cached and
re-used if the `results_cache` parameter was set when instantiating
the class.
```

**Comment by alimanfoo** [comment]
Just updated to use a more concise approach. E.g., here is the decorator and signature for the `snp_allele_counts()` method:

```
    @doc(
        summary="""
            Compute SNP allele counts. This returns the number of times each
            SNP allele was observed in the selected samples.
        """,
        parameters=parameters,
        returns="""
            A numpy array of shape (n_variants, 4), where the first column has
            the reference allele (0) counts, the second column has the first
            alternate allele (1) counts, the third column has the second
            alternate allele (2) counts, and the fourth column has the third
            alternate allele (3) counts.
        """,
        notes="""
            This computation may take some time to run, depending on your
            computing environment. Results of this computation will be cached
            and re-used if the `results_cache` parameter was set when
            instantiating the class.
        """,
    )
    def snp_allele_counts(
        self,
        region: types.region,
        sample_sets: Optional[types.sample_sets] = None,
        sample_query: Optional[types.sample_query] = None,
        site_mask: Optional[types.site_mask] = None,
        site_class: Optional[types.site_class] = None,
        cohort_size: Optional[types.cohort_size] = None,
        random_seed: Optional[types.random_seed] = 42,
    ) -> np.ndarray:
   ...
```

**Comment by alimanfoo** [comment]
E.g., here's the doc annotation and type hints for the `snp_allele_counts()` method:

```python
    @doc(
        summary="""
            Compute SNP allele counts. This returns the number of times each
            SNP allele was observed in the selected samples.
        """,
        parameters=param_docs,
        returns="""
            A numpy array of shape (n_variants, 4), where the first column has
            the reference allele (0) counts, the second column has the first
            alternate allele (1) counts, the third column has the second
            alternate allele (2) counts, and the fourth column has the third
            alternate allele (3) counts.
        """,
        notes="""
            This computation may take some time to run, depending on your
            computing environment. Results of this computation will be cached
            and re-used if the `results_cache` parameter was set when
            instantiating the class.
        """,
    )
    def snp_allele_counts(
        self,
        region: params.region,
        sample_sets: Optional[params.sample_sets] = None,
        sample_query: Optional[params.sample_query] = None,
        site_mask: Optional[params.site_mask] = None,
        site_class: Optional[params.site_class] = None,
        cohort_size: Optional[params.cohort_size] = None,
        random_seed: Optional[params.random_seed] = 42,
    ) -> np.ndarray:
   ...
```

...and here's how the docstring comes out:

```
Compute SNP allele counts. This returns the number of times each SNP
allele was observed in the selected samples.

Parameters
----------
region : str or Region
    Contig name, region string (formatted like "{contig}:{start}-{end}"),
    or identifier of a genome feature such as a gene or transcript.
sample_sets : Sequence[str] or str or None, optional
    List of sample sets and/or releases. Can also be a single sample set
    or release.
sample_query : str or None, optional
    A pandas query string to be evaluated against the sample metadata.
site_mask : str or None, optional
    Which site filters mask to apply. See the `site_mask_ids` property for
    available values.
site_class : str or None, optional
    Select sites belonging to one of the following classes: CDS_DEG_4,
    (4-fold degenerate coding sites), CDS_DEG_2_SIMPLE (2-fold simple
    degenerate coding sites), CDS_DEG_0 (non-degenerate coding sites),
    INTRON_SHORT (introns shorter than 100 bp), INTRON_LONG (introns
    longer than 200 bp), INTRON_SPLICE_5PRIME (intron within 2 bp of 5'
    splice site), INTRON_SPLICE_3PRIME (intron within 2 bp of 3' splice
    site), UTR_5PRIME (5' untranslated region), UTR_3PRIME (3'
    untranslated region), INTERGENIC (intergenic, more than 10 kbp from a
    gene).
cohort_size : int or None, optional
    Randomly down-sample to the given cohort size.
random_seed : int or None, optional, default: 42
    Random seed used for reproducible down-sampling.

Returns
-------
ndarray
    A numpy array of shape (n_variants, 4), where the first column has the
    reference allele (0) counts, the second column has the first alternate
    allele (1) counts, the third column has the second alternate allele
    (2) counts, and the fourth column has the third alternate allele (3)
    counts.

Notes
-----
This computation may take some time to run, depending on your
computing environment. Results of this computation will be cached and
re-used if the `results_cache` parameter was set when instantiating
the class.
```

**Comment by alimanfoo** [comment]
OK, I think I'm done here. Here's an example of how the function documentation now looks:

```python
    @doc(
        summary="""
            Compute SNP allele counts. This returns the number of times each
            SNP allele was observed in the selected samples.
        """,
        returns="""
            A numpy array of shape (n_variants, 4), where the first column has
            the reference allele (0) counts, the second column has the first
            alternate allele (1) counts, the third column has the second
            alternate allele (2) counts, and the fourth column has the third
            alternate allele (3) counts.
        """,
        notes="""
            This computation may take some time to run, depending on your
            computing environment. Results of this computation will be cached
            and re-used if the `results_cache` parameter was set when
            instantiating the class.
        """,
    )
    def snp_allele_counts(
        self,
        region: base_params.region,
        sample_sets: Optional[base_params.sample_sets] = None,
        sample_query: Optional[base_params.sample_query] = None,
        site_mask: Optional[base_params.site_mask] = None,
        site_class: Optional[base_params.site_class] = None,
        cohort_size: Optional[base_params.cohort_size] = None,
        random_seed: base_params.random_seed = 42,
    ) -> np.ndarray:
    ...
```

Note that the parameter types like `base_params.sample_sets` have documentation embedded via the use of the `Annotated` type.

Here's how the docstring looks via the `help()` function:

```
Help on method snp_allele_counts in module malariagen_data.anopheles:

snp_allele_counts(region: Union[str, malariagen_data.util.Region], sample_sets: Union[Sequence[str], str, NoneType] = None, sample_query: Optional[str] = None, site_mask: Optional[str] = None, site_class: Optional[str] = None, cohort_size: Optional[int] = None, random_seed: int = 42) -> numpy.ndarray method of malariagen_data.ag3.Ag3 instance
    Compute SNP allele counts. This returns the number of times each SNP
    allele was observed in the selected samples.
    
    Parameters
    ----------
    region : str or Region
        Region of the reference genome. Can be a contig name, region string
        (formatted like "{contig}:{start}-{end}"), or identifier of a genome
        feature such as a gene or transcript.
    sample_sets : sequence of str or str or None, optional
        List of sample sets and/or releases. Can also be a single sample set
        or release.
    sample_query : str or None, optional
        A pandas query string to be evaluated against the sample metadata.
    site_mask : str or None, optional
        Which site filters mask to apply. See the `site_mask_ids` property for
        available values.
    site_class : str or None, optional
        Select sites belonging to one of the following classes: CDS_DEG_4,
        (4-fold degenerate coding sites), CDS_DEG_2_SIMPLE (2-fold simple
        degenerate coding sites), CDS_DEG_0 (non-degenerate coding sites),
        INTRON_SHORT (introns shorter than 100 bp), INTRON_LONG (introns
        longer than 200 bp), INTRON_SPLICE_5PRIME (intron within 2 bp of 5'
        splice site), INTRON_SPLICE_3PRIME (intron within 2 bp of 3' splice
        site), UTR_5PRIME (5' untranslated region), UTR_3PRIME (3'
        untranslated region), INTERGENIC (intergenic, more than 10 kbp from a
        gene).
    cohort_size : int or None, optional
        Randomly down-sample to the given cohort size.
    random_seed : int, optional, default: 42
        Random seed used for reproducible down-sampling.
    
    Returns
    -------
    ndarray
        A numpy array of shape (n_variants, 4), where the first column has the
        reference allele (0) counts, the second column has the first alternate
        allele (1) counts, the third column has the second alternate allele
        (2) counts, and the fourth column has the third alternate allele (3)
        counts.
    
    Notes
    -----
    This computation may take some time to run, depending on your
    computing environment. Results of this computation will be cached and
    re-used if the `results_cache` parameter was set when instantiating
    the class.
```

**Comment by alimanfoo** [comment]
Hi @leehart, @cclarkson, @sanjaynagi, FYI some changes proposed here for how we do function docstrings. This is ready for review, any comments or questions welcome. Diff is big and may be hard to navigate so give me a shout if you'd like me to talk it through.

N.B., I might hold off merging this PR until other opens PRs are in master, better to handle any awkward conflicts here.

**Comment by sanjaynagi** [comment]
This looks really cool @alimanfoo , makes sense that we shouldn't repeat all the docstrings every time! Will be good to talk through though. Intrigued as to how you make a decorator.

**Comment by alimanfoo** [comment]
> This looks really cool @alimanfoo , makes sense that we shouldn't repeat all the docstrings every time! Will be good to talk through though. Intrigued as to how you make a decorator.

Cool, thanks @sanjaynagi. Source code for the [@doc decorator is here](https://github.com/alimanfoo/numpydoc_decorator/blob/2b8c66abb4c984f0e5f34cb0f8020639ee20632b/numpydoc_decorator/impl.py#L427), decorators can be a bit mind-bending at first but can be useful. You just need to write a function that returns a function that returns a function :) Would be cool to talk through.

**Comment by alimanfoo** [comment]
Alright, G123 functions have been merged here and given the `@doc` treatment. Will merge here if CI is happy.

**Pull request merged**
