### PR TITLE
Add Af1 site filters track for view_alignments()

### PR DESCRIPTION
**Pull request by leehart**
Re: #335

### CODE REVIEW

**Comment by leehart** [comment]
```
=================================== FAILURES ===================================
_____________________ test_snp_sites_for_joined_arms[3RL] ______________________

chrom = '3RL'

    @pytest.mark.parametrize("chrom", ["2RL", "3RL"])
    def test_snp_sites_for_joined_arms(chrom):
        ag3 = setup_ag3()
        contig_r = chrom[0] + chrom[1]
        contig_l = chrom[0] + chrom[2]
        sites_r = ag3.snp_sites(region=contig_r, field="POS")
        sites_l = ag3.snp_sites(region=contig_l, field="POS")
        max_r = ag3.genome_sequence(region=contig_r).shape[0]
        sites_expected = da.concatenate([sites_r, sites_l + max_r])
        sites_actual = ag3.snp_sites(region=chrom, field="POS")
    
        assert isinstance(sites_actual, da.Array)
        assert sites_actual.ndim == 1
        assert sites_actual.dtype == "int32"
>       assert np.all(sites_expected == sites_actual)

tests/test_ag3.py:378: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[...]
=========================== short test summary info ============================
FAILED tests/test_ag3.py::test_snp_sites_for_joined_arms[3RL] - RuntimeError: error during blosc decompression: -1
```

**Comment by sanjaynagi** [comment]
Hi @leehart,  just to say that the blosc error for the above test failure should be resolved now with the merging of #355 

The fix was described by Alistair in a different PR #354 - 
https://github.com/malariagen/malariagen-data-python/pull/354#discussion_r1132615657

**Comment by leehart** [comment]
Awesome, thanks @sanjaynagi !

**Review by alimanfoo — APPROVED** [review]
Awesome, thanks @leehart. I ran the igv notebook to confirm this is working.

**Pull request merged**
