### PR TITLE
Add support for cohorts metadata in Af1

### PR DESCRIPTION
**Pull request by leehart**
Ref https://github.com/malariagen/malariagen-data-python/issues/315

### CODE REVIEW

**Comment by leehart** [comment]
Functions checklist:
- [x] snp_allele_frequencies() in Parent
- [x] aa_allele_frequencies() in Parent
- [x] plot_frequencies_heatmap() in Parent
- [x] snp_allele_frequencies_advanced() in Children (diff filters)
- [x] aa_allele_frequencies_advanced() in Parent
- [x] plot_frequencies_time_series() in Parent
- [x] plot_frequencies_map_markers() in Parent
- [x] plot_frequencies_interactive_map() in Parent
- [x] snp_allele_counts() in Children (diff caches)
- [x] plot_pca_coords() in Parent
- [x] plot_pca_coords_3d() in Parent
- [x] cohort_diversity_stats() in Parent
- [x] diversity_stats() in Parent
- [x] plot_diversity_stats() in Parent
- [x] plot_samples_interactive_map() in Parent
- [x] count_samples() in Parent
- [x] fst_gwss() - in Children (diff caches)
- [x] plot_fst_gwss_track() - in Parent and Children (override default site_mask)
- [x] plot_fst_gwss() - in Parent and Children (override default site_mask)

**Comment by leehart** [comment]
To do later, maybe:
- Develop `snp_effects()` test for Af1.0. The data appear incomplete, which makes testing difficult.
- Compare `diversity_stats()` with `cohort_diversity_stats()`, now both in the parent class.
- Produce API doc for Af1.0, for `__repr__`, `_repr_html_` https://malariagen.github.io/vector-data/af1/api.html

**Comment by leehart** [comment]
@alimanfoo  @cclarkson  I think I need a good way to test and debug the plotting functions.
I suspect there might be errors around the `results_cache`, but it might just be the way I'm trying to test things.

**Comment by leehart** [comment]
@jorels1

**Review by alimanfoo — COMMENTED** [review]
Couple of small comments from an initial pass. All looks good generally, but I'll take a more thorough look asap.

**Comment by leehart** [comment]
Thanks @alimanfoo . Ready for re-review?

**Comment by alimanfoo** [comment]
Thanks @leehart. I'm going to make another PR to add some additional checks into the notebooks using Af1, to verify the new functionality is available and working as expected. This should also verify plotting functions. I'll make another PR against your fork.

**Review by alimanfoo — APPROVED** [review]
Thanks Lee, good to go AFAIC.

**Pull request merged**
