### PR TITLE
Add terms-of-use info to sample_metadata()

### PR DESCRIPTION
**Pull request by leehart**
Re: issue #508

### CODE REVIEW

**Comment by leehart** [comment]
- [ ] Pending agreement on `unrestricted_use` column name or alternative.

**Comment by leehart** [comment]
`codecov` checks complain about `malariagen_data/anoph/base.py` with `with 4 lines in your changes missing coverage`, which were apparently OK before updating from the master branch, again.

It's frustrating that this sort of shenanigans keeps blocking innocent PRs. 😞

**Comment by leehart** [comment]
Ref: https://github.com/malariagen/malariagen-data-python/issues/554

**Review by alimanfoo — APPROVED** [review]
LGTM :)

**Comment by leehart** [comment]
Thanks @alimanfoo .

On second glance, `codecov/patch` actually has a point that the new `lookup_study_info` and `lookup_terms_of_use_info` aren't covered by tests. I'll try to add those before merging, probably next week.

**Review by ahernank — APPROVED** [review]
Thanks @leehart! 

FYI, I was just catching-up with @alimanfoo; and he'd be happy to merge this one without adding any further tests to appease codecov, if you are happy with this (as they refer to the try/exempt; and the decrease in coverage might also be partially explained by a total reduction of lines of codes in the codebase).

**Comment by leehart** [comment]
OK, I see, thanks @ahernank . Happy to merge this in now and face the wrath of codecov!

**Pull request merged**
