### PR TITLE
Add variance vars to CNV HMM

### PR DESCRIPTION
**Pull request by leehart**
Ref [#1540](https://github.com/malariagen/vector-ops/issues/1540)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @leehart, just to say this looks spot on, I guess it's failing CI as the data are in the release bucket yet. Happy to approve this now and then you can merge when data are in place and CI is passing?

**Comment by leehart** [comment]
> Hi @leehart, just to say this looks spot on, I guess it's failing CI as the data are in the release bucket yet. Happy to approve this now and then you can merge when data are in place and CI is passing?

I expect so. I was hoping to figure out a way to test & pass while still in the staging bucket, but I suspect that's overkill.

**Comment by leehart** [comment]
@alimanfoo CI checks are still failing despite the new data being in the release bucket. Investigating.

**Comment by leehart** [comment]
The failed tests seem to pass locally, so I'm starting to wonder if this is a caching issue again, but I'm not completely sure what the tests are doing yet.

**Comment by leehart** [comment]
I tried rerunning the CI checks after an hour but got the same result, so if it is a caching issue it seems different or longer lasting than the consolidated Zarr metadata one.

**Comment by leehart** [comment]
@alimanfoo CI checks passed after reconsolidating the recently released CNV data, including tests for `test_cnv_discordant_read_calls`

**Review by alimanfoo — APPROVED** [review]
Thanks Lee, going to merge.

**Pull request merged**
