### PR TITLE
Refactor haplotypes functions to support Af1

### PR DESCRIPTION
**Pull request by leehart**
Re: https://github.com/malariagen/malariagen-data-python/issues/313

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @leehart, couple of small suggestions over in https://github.com/leehart/malariagen-data-python/pull/5, but otherwise this is looking good to me. That PR includes a fix for the tests failing CI here, so once that is merged hopefully CI will pass here.

Once CI is passing, only other suggestion would be to add some funestus examples to the notebooks that exercise some haplotype-based analyses. Currently there are three notebooks which do that - plot_h1x, plot_haplotype_clustering and plot_haplotype_networks. Give me a shout if you'd like any help with that.

**Comment by leehart** [comment]
Hi @alimanfoo . Many thanks! I should point out that this PR is still in draft, so I wasn't quite expecting a review yet!
I still have uncommitted work, so there has been some duplication of effort.

**Comment by alimanfoo** [comment]
> Hi @alimanfoo . Many thanks! I should point out that this PR is still in draft, so I wasn't quite expecting a review yet! I still have uncommitted work, so there has been some duplication of effort.

Hi @leehart, sorry I'm being too keen - feel free to tell me to remove stuff from my PR (or drop it entirely) if you already have changes coming here :slightly_smiling_face:

**Comment by leehart** [comment]
Support for accessing Af1.0 haplotypes:
- [x] open_haplotypes()
- [x] open_haplotype_sites()
- [x] haplotypes()

Support for analytical functions
- [x] h12_calibration()
- [x] plot_h12_calibration()
- [x] h12_gwss()
- [x] plot_h12_gwss_track()
- [x] plot_h12_gwss()
- [x] h1x_gwss()
- [x] plot_h1x_gwss_track()
- [x] plot_h1x_gwss()
- [x] plot_haplotype_clustering()
- [x] plot_haplotype_network()

Notebooks:
- [ ] plot_h1x
- [ ] plot_haplotype_clustering
- [ ] plot_haplotype_networks

**Comment by leehart** [comment]
Hi @alimanfoo 

I tried adding Af1 examples to the haplotype notebooks, but I ran into a couple of errors that I haven't resolved yet. (I'm trying to use Visual Studio Code to run the notebooks, because PyCharm "CE" doesn't have that feature.)

WRT `plot_h1x.ipynb`, I get a CacheMiss and ValueError, telling me `No samples found for query "cohort_admin2_year == '{coh1}'"`, where `coh1` is "GH-NP_Tolon-Kumbungu_fune_2017" or "GH-NP_Zabzugu-Tatale_fune_2017", which I am expecting to have samples. The Ag3 examples run fine, so I'm expecting something like a typo or false assumption.

WRT `plot_haplotype_networks.ipynb`, I get the following kind of error for both Ag3 and Af1 examples, which corresponds to one of the warnings I see in my PyCharm dev env, near to other warnings concerning unresolved references for dash.
```
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/kb/979qwblj4qv6330vn5d4qq3w0000gn/T/ipykernel_9433/3322301523.py in <cell line: 1>()
----> 1 ag3.plot_haplotype_network(
      2     region="2L:2,358,158-2,431,617",
      3     analysis="gamb_colu",
      4     sample_query="taxon == 'coluzzii'",
      5     color="country",

~/Desktop/work/gitRepos/malariagen-data-python/malariagen_data/anopheles.py in plot_haplotype_network(self, region, analysis, sample_sets, sample_query, max_dist, color, color_discrete_sequence, color_discrete_map, category_orders, node_size_factor, server_mode, height, width, layout, layout_params, server_port)
   7921         from itertools import cycle
   7922 
-> 7923         import dash_cytoscape as cyto
   7924         import plotly.express as px
   7925         from dash import dcc, html

ModuleNotFoundError: No module named 'dash_cytoscape'
```

**Review by alimanfoo — APPROVED** [review]
Woohoo, LGTM :rocket:

**Comment by alimanfoo** [comment]
Amazing, thanks @leehart! I ran through the notebooks and the Af1 examples work beautifully. All looks good to me, feel free to merge when CI passes. Have a good weekend :slightly_smiling_face:

**Comment by leehart** [comment]
Re-running:
```
[notebooks (3.7, 1.3.1, ubuntu-latest)](https://github.com/malariagen/malariagen-data-python/actions/runs/4087321246/jobs/7047685047)
The job running on runner GitHub Actions 6 has exceeded the maximum execution time of 360 minutes.
```

**Comment by leehart** [comment]
```
[NbConvertApp] Converting notebook notebooks/plot_haplotype_clustering.ipynb to notebook
/home/runner/.cache/pypoetry/virtualenvs/malariagen-data-XR4NpaW--py3.7/lib/python3.7/site-packages/nbformat/__init__.py:93: DuplicateCellId: Non-unique cell id '38abbb28' detected. Corrected to '87f36d07'.
  validate(nb)
/home/runner/.cache/pypoetry/virtualenvs/malariagen-data-XR4NpaW--py3.7/lib/python3.7/site-packages/nbformat/__init__.py:93: DuplicateCellId: Non-unique cell id 'ccb2366f' detected. Corrected to 'e1f68c6c'.
  validate(nb)
/home/runner/.cache/pypoetry/virtualenvs/malariagen-data-XR4NpaW--py3.7/lib/python3.7/site-packages/nbformat/__init__.py:93: DuplicateCellId: Non-unique cell id '857145af' detected. Corrected to '5bc93110'.
  validate(nb)
/home/runner/.cache/pypoetry/virtualenvs/malariagen-data-XR4NpaW--py3.7/lib/python3.7/site-packages/nbformat/__init__.py:93: DuplicateCellId: Non-unique cell id 'f[41](https://github.com/malariagen/malariagen-data-python/actions/runs/4087321246/jobs/7055514287#step:7:42)b7e63' detected. Corrected to '45bdce7c'.
  validate(nb)
[NbConvertApp] Writing 7671197 bytes to notebooks/plot_haplotype_clustering.ipynb
[NbConvertApp] Converting notebook notebooks/plot_haplotype_networks.ipynb to notebook
[NbConvertApp] WARNING | No handler found for comm target 'jupyter_dash'
##[debug]Re-evaluate condition on job cancellation for step: 'Run notebooks'.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Run notebooks
```

**Pull request merged**
