### PR TITLE
Random error when performing tests

### PR DESCRIPTION
**Pull request by jonbrenas**
Addresses #618 .

### CODE REVIEW

**Review by leehart — APPROVED** [review]
Thanks @jonbrenas .

I'm not sure about the `assert`. I suppose the idea is that it will fail if either the number of samples or the number of SNPs is 3 or fewer. I expect there would be a `ValueError` raised in `randint` if `n_snps_available` was fewer than 4, so I expect `n_snps` will be at least 4 at the `assert` and so it might boil down to `n_samples`. Perhaps we might want a way to either ensure enough samples and SNPs at this point, or otherwise raise a clear error when that hasn't happened. But perhaps that's a different problem for a different day!

**Comment by leehart** [comment]
By the way, I don't quite understand the commit that "Drops a few unused columns", which doesn't come through as a change, presumably due to having an identical change being already merged in from master? Was that commit related to the same issue, or an artefact of something else perhaps?

**Comment by jonbrenas** [comment]
Thanks @leehart .

The `assert` should never be `False` unless the test is really poorly setup. `n_samples` is the sum of the sizes of the two randomly chosen sample sets and `n_snps_available` is the number of biallelic SNPs in the randomly chosen chromosome arm using all these samples. Both values should be significantly higher than 4.

The commits have been part of all my PRs for a while. I am not sure why. I hope they disappear once one of these PRs is merged into master.

**Comment by leehart** [comment]
Thanks @jonbrenas 
CI tests failed on unrelated PCA tests. I'll try re-running.
> =========================== short test summary info ============================
> FAILED tests/anoph/test_pca.py::test_pca_exclude_samples[af1_sim] - ValueError: empty range in randrange(3, 3)
> =========== 1 failed, 379 passed, 322 warnings in 424.39s (0:07:04) ============

**Comment by jonbrenas** [comment]
It actually fails on exactly the test that I modified because it can sometimes randomly fail on unrelated PRs (but this PR has to pass the previous tests for it to be approved, obviously, which it now does).

**Comment by leehart** [comment]
Haha, I see, of course. Thanks @jonbrenas . OK if I delete the branch from GitHub now it's been merged in?

**Comment by jonbrenas** [comment]
Done!

**Pull request merged**
