### PR TITLE
Add support for writing Anopheles SNP data to the plink binary file format (shadow PR)

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR shadows #515 to get GitHub actions running.

### CODE REVIEW

**Comment by jonbrenas** [comment]
Tristan has included a notebook in his PR to test the PLINK converter functions. The main issue is that it creates a .bed file which raises issues with correct paths (there also seems to be a problem with authentication when he ran it locally but that’s neither here nor there). I think the best solution is to stop tracking the notebook. @alimanfoo, @ahernank, @cclarkson, @leehart, any opinion?

**Comment by alimanfoo** [comment]
Hi @jonbrenas, apologies, I think we might be both working here at the same time...

**Comment by alimanfoo** [comment]
Commit [643534e](https://github.com/malariagen/malariagen-data-python/pull/584/commits/643534e7642a9cfaade66bb8bf13bc108c255996) should be the latest in both PRs.

**Comment by alimanfoo** [comment]
To bring this PR back into sync with #515 I reckon we should do:

```
git checkout plink-converter-2024-03-26-tristanpwdennis-shadow
git reset --hard 643534e
git push --force
```

**Comment by alimanfoo** [comment]
Cool, thanks @jonbrenas. I've manually triggered the actions to rerun, just so we can be sure any failures are real and up to date with the current state of this PR. 

If we see any failures, let's investigate and feed back any suggestions to Tristan via #515.

**Comment by alimanfoo** [comment]
The notebooks check is failing in a notebook that is unrelated to this PR with what looks like a transient error trying to check the client location:

```
File ~/work/malariagen-data-python/malariagen-data-python/malariagen_data/anoph/base.py:96, in AnophelesBase.__init__(self, url, config_path, pre, major_version_number, major_version_path, gcs_default_url, gcs_region_urls, bokeh_output_notebook, log, debug, show_progress, check_location, storage_options, results_cache, tqdm_class)
     94 if check_location:
     95     try:
---> 96         self._client_details = ipinfo.getHandler().getDetails()
     97     except OSError:
     98         pass
File ~/.cache/pypoetry/virtualenvs/malariagen-data-XR4NpaW--py3.12/lib/python3.12/site-packages/ipinfo/handler.py:132, in Handler.getDetails(self, ip_address, timeout)
    130     else:
    131         error_response = ***'error': response.text***
--> 132     raise APIError(error_code, error_response)
    133 details = response.json()
    135 # format & cache
APIError: APIError: 503
***
  "error": "upstream connect error or disconnect/reset before headers. reset reason: connection timeout"
***
```

Perhaps ignore for the moment, but we could turn off client checks if this becomes a problem.

**Comment by alimanfoo** [comment]
Unit tests are failing with:

```
________________________ test_plink_converter[af1_sim] _________________________

fixture = <tests.anoph.conftest.Af1Simulator object at 0x7fd253446d90>
api = <malariagen_data.anoph.to_plink.PlinkConverter object at 0x7fd24806f250>
tmp_path = PosixPath('/tmp/pytest-of-runner/pytest-0/test_plink_converter_af1_sim_0')

    @parametrize_with_cases("fixture,api", cases=".")
    def test_plink_converter(fixture, api: PlinkConverter, tmp_path):
        # Parameters for selecting input data, filtering, and converting.
        all_sample_sets = api.sample_sets()["sample_set"].to_list()
    
        data_params = dict(
            region=random.choice(api.contigs),
            sample_sets=random.sample(all_sample_sets, 2),
            site_mask=random.choice((None,) + api.site_mask_ids),
            min_minor_ac=1,
            max_missing_an=1,
            thin_offset=1,
            random_seed=random.randint(1, 2000),
        )
    
        # Load a ds containing the randomly generated samples and regions to get the number of available snps to subset from.
        ds = api.biallelic_snp_calls(
            **data_params,
        )
    
        n_snps_available = ds.sizes["variants"]
        n_snps = random.randint(1, n_snps_available)
    
        # Define plink params.
        plink_params = dict(results_dir=tmp_path, n_snps=n_snps, **data_params)
    
        # Make the plink files.
>       api.biallelic_snps_to_plink(**plink_params)
E       TypeError: PlinkConverter.biallelic_snps_to_plink() got an unexpected keyword argument 'results_dir'

tests/anoph/test_plink_converter.py:105: TypeError
```

**Comment by jonbrenas** [comment]
Yes, it should be `output_dir` instead of `results_dir`. @alimanfoo, do you want me to forward this change to @tristanpwdennis now or to solve all the issues here as they arise (taking notes) and then recommend he does the same modifications in his PR?

**Comment by tristanpwdennis** [comment]
Hi guys, I fixed the test notebook and the local tests are now completing successfully
Cheers!

**Comment by alimanfoo** [comment]
Thanks @tristanpwdennis, unit tests are now passing :)

[Looks like](https://github.com/malariagen/malariagen-data-python/actions/runs/11930657680/job/33251872588?pr=584#step:10:34) the plink_convert notebook also needs to be updated though to use "output_dir" instead of "results_dir".

**Comment by tristanpwdennis** [comment]
Whoops, sorry, please blame the psychotropic jetlag. Fixed this now, and updated the output path to be the notebook dir (as opposed to a relative path on my local!). Hope this is OK?

**Review by jonbrenas — APPROVED** [review]
LGTM and approved by @alimanfoo here: https://github.com/malariagen/malariagen-data-python/pull/515

**Pull request merged**
